### ISSUE TITLE
OCP_VER has been updated from 4.3.18 to 4.3.29

### ISSUE THREAD

**Issue by imicer** [liuxiaoyu-git/ocp4-bm-install#1]
I am preparing for installing OCP4.3.

From the OCP4 离线裸机部署手册-workshop-v0.6.6.4.docx
I tried to run the following command:
export OCP_VER=$(curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.3/release.txt | \grep 'Name:' | awk '{print $NF}')
The output of the command "echo ${OCP_VER} " is 4.3.29 on Jul 24. 
I found the vaule was still 4.3.18 before Jul 20.
So I have to use this version of 4.3.29 for OCP installation.
Can I use this version of 4.3.29 to change hardcode in your script including 2-parameter.sh and so on?
Or what do I need change based on the version of 4.3.29?

Any feedback on this issue will be appreciated.

Thanks.

**Comment by liuxiaoyu-git** [comment]
You can change OCP_VER to 4.3.29 directly and download all OCP images following my doc.

**Comment by imicer** [comment]
Thanks for your reply.
