### ISSUE TITLE
how to create vm using kvm?

### ISSUE THREAD

**Issue by imicer** [liuxiaoyu-git/ocp4-bm-install#2]
Thanks for your materials.
From your docx,
Now I can go through 1-5 sections in my env. 
In 6 section, I failed to create Bootstrap、Master、Worker vms.
In my host machine which bare metal, 
I tired to use the virt-install command to create boorstrap vm image, 
the following error message is output:

virt-install --name=ocp43bootstrap --ram 10240 --vcpus=2 \
> --disk path=/infer_local2/OCP43/image4kvm/ocp43bootstrap.img,size=100 \
> --accelerate --location http://yum.example.internal:8080/rhcos-iso/ocp4-1/bootstrap.iso  \
> --graphics vnc,listen=192.168.1.12,port=5920  \
> --network network=enp0s3 --network bridge=virbr2  --force  --autostart
ERROR    Error validating install location: Could not find an installable distribution at 'http://yum.example.internal:8080/rhcos-iso/ocp4-1/bootstrap.iso'

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.

Could you help tell me how to create three vms using kvm?

Thank you very much.
Yun

**Comment by liuxiaoyu-git** [comment]
Don't  boot VM with http://yum.example.internal:8080/rhcos-iso/ocp4-1/bootstrap.iso. You must copy all iso files to Linux file system and boot vm with local iso.

**Comment by imicer** [comment]
Thanks for your reminding.
I have copy all iso files into my location path.
Now I can create maser/work0/work1 vms.
I will close this issue.
Thanks a lot.

Yun
