### ISSUE TITLE
Could you help provide  <liuxiaoyu-git/OCP4-Install-Guide/OCP4 离线裸机部署手册-workshop-v0.6.6.x.docx>

### ISSUE THREAD

**Issue by imicer** [liuxiaoyu-git/ocp4-bm-install#7]
Hi Xiao Yu

I notice you have updated the repo recently, but I didn't find the doc  <liuxiaoyu-git/OCP4-Install-Guide/OCP4 离线裸机部署手册-workshop-v0.6.6.x.docx> you mentioned in README.
Could you help upload the documents as reference?

Thanks.
Yun

**Comment by liuxiaoyu-git** [comment]
https://github.com/liuxiaoyu-git/OCP4-Install-Guide

 

发件人: imicer <notifications@github.com> 
发送时间: 2020年10月26日 11:44
收件人: liuxiaoyu-git/ocp4-bm-install <ocp4-bm-install@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [liuxiaoyu-git/ocp4-bm-install] Could you help provide <liuxiaoyu-git/OCP4-Install-Guide/OCP4 离线裸机部署手册-workshop-v0.6.6.x.docx> (#7)

 

Hi Xiao Yu

I notice you have updated the repo recently, but I didn't find the doc <liuxiaoyu-git/OCP4-Install-Guide/OCP4 离线裸机部署手册-workshop-v0.6.6.x.docx> you mentioned in README.
Could you help upload the documents as reference?

Thanks.
Yun

**Comment by imicer** [comment]
Thanks for your help.
